alias work="cd ~/Documents/Work"
alias server="python -m SimpleHTTPServer"
alias httpd="atom /Applications/MAMP/conf/apache/httpd.conf"
alias copyatom="cp -R ~/.atom /Users/dyankov/Documents/github/atom-dotfiles/"
alias copybash="cp ~/.bash_profile ~/Documents/github/dotfiles/"
alias todo="atom ~/Documents/Work/other/work.php"
alias add="git add -A ."
